- name: Copy docker-compose file to remote server
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: /home/ismail/docker-compose.yaml

- name: Docker login to dockerhub private registry
  community.docker.docker_login:
    registry_url: "{{ docker_registry_url }}"
    username: "{{ docker_username}}"
    password: "{{ docker_password }}"

- name: Start docker containers using docker-compose
  community.docker.docker_compose:
    project_src: /home/ismail/
    state: present